In [2]:
import pandas as pd

In [3]:
nyc_accidents = pd.read_csv("data/accidents-nyc.csv")

In [4]:
nyc_accidents

,CRASH DATE,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
0,4/13/21,21:35,BROOKLYN,1,0,1,0,0,0,0,0,Unspecified,NaN,4407147,Sedan,NaN
1,4/13/21,16:00,BROOKLYN,0,0,0,0,0,0,0,0,Following Too Closely,Unspecified,4407811,Sedan,NaN
2,4/13/21,17:30,QUEENS,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4408019,Sedan,Sedan
3,4/11/21,21:06,BROOKLYN,1,0,1,0,0,0,0,0,Passing Too Closely,NaN,4406488,Taxi,NaN
4,4/15/21,20:00,STATEN ISLAND,0,0,0,0,0,0,0,0,Unspecified,NaN,4408310,Sedan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282868,1/1/19,19:00,BROOKLYN,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4060606,Ambulance,Sedan
282869,1/1/19,8:00,BRONX,0,0,0,0,0,0,0,0,Steering Failure,Unspecified,4060771,Pick-up Truck,Station Wagon/Sport Utility Vehicle
282870,1/1/19,3:30,BRONX,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4060653,Pick-up Truck,Sedan
282871,1/1/19,19:30,BROOKLYN,0,0,0,0,0,0,0,0,Passing Too Closely,Unspecified,4268108,Tanker,Sedan
282872,1/1/19,12:00,MANHATTAN,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4060666,Sedan,NaN

In [5]:
nyc_accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282873 entries, 0 to 282872
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH DATE                     282873 non-null  object
 1   CRASH TIME                     282873 non-null  object
 2   BOROUGH                        282873 non-null  object
 3   NUMBER OF PERSONS INJURED      282873 non-null  int64
 4   NUMBER OF PERSONS KILLED       282873 non-null  int64
 5   NUMBER OF PEDESTRIANS INJURED  282873 non-null  int64
 6   NUMBER OF PEDESTRIANS KILLED   282873 non-null  int64
 7   NUMBER OF CYCLIST INJURED      282873 non-null  int64
 8   NUMBER OF CYCLIST KILLED       282873 non-null  int64
 9   NUMBER OF MOTORIST INJURED     282873 non-null  int64
 10  NUMBER OF MOTORIST KILLED      282873 non-null  int64
 11  CONTRIBUTING FACTOR VEHICLE 1  281489 non-null  object
 12  CONTRIBUTING FACTOR VEHICLE 2  224591 non-null  object
 13  COLLISION_ID                   282873 non-null  int64
 14  VEHICLE TYPE CODE 1            279986 non-null  object
 15  VEHICLE TYPE CODE 2            201168 non-null  object
dtypes: int64(9), object(7)
memory usage: 34.5+ MB

In [7]:
nyc_crash_dates = nyc_accidents["CRASH DATE"]

In [8]:
nyc_crash_dates.head()

0    4/13/21
1    4/13/21
2    4/13/21
3    4/11/21
4    4/15/21
Name: CRASH DATE, dtype: object

In [27]:
nyc_accidents["BOROUGH"].unique()

array(['BROOKLYN', 'QUEENS', 'STATEN ISLAND', 'BRONX', 'MANHATTAN'],
      dtype=object)

In [29]:
nyc_accidents["BOROUGH"].value_counts()

BROOKLYN         95099
QUEENS           80085
BRONX            50123
MANHATTAN        48864
STATEN ISLAND     8702
Name: BOROUGH, dtype: int64

In [30]:
## Brooklyn has the most accidents

In [32]:
nyc_accidents["VEHICLE TYPE CODE 1"].value_counts().head(7)
## Top vehicles involved in accidents

Sedan                                  129987
Station Wagon/Sport Utility Vehicle    102850
Taxi                                    10647
Pick-up Truck                            7183
Box Truck                                5504
Bus                                      4697
Bike                                     3177
Name: VEHICLE TYPE CODE 1, dtype: int64

In [33]:
nyc_accidents["VEHICLE TYPE CODE 1"].value_counts().tail()
##If "unusual" means infrequent, these are the vehicles involved 
##in accidents infrequently

SLINGSHOT     1
CHEVY EXPR    1
Go kart       1
FDNY Engin    1
MAC T         1
Name: VEHICLE TYPE CODE 1, dtype: int64

In [34]:
nyc_accidents["VEHICLE TYPE CODE 1"].unique()

array(['Sedan', 'Taxi', 'ï¿½MBU', 'Station Wagon/Sport Utility Vehicle',
       'Pick-up Truck', nan, 'Ambulance', 'Tow Truck / Wrecker', 'E-Bike',
       'Van', 'Moped', 'Tractor Truck Diesel', 'AMBULANCE', 'Bike',
       'Trailer', 'Bus', 'Box Truck', 'Motorcycle', 'Lift Boom',
       'scooter', 'CATER', 'FDNY Ambul', '3-Door', 'SEMI TRAIL', 'Dump',
       'Convertible', '4 dr sedan', 'dump', 'Flat Rack', 'Flat Bed',
       'GARBAGE TR', 'Tanker', 'Carry All', 'Armored Truck',
       'Garbage or Refuse', 'SCHOOL BUS', 'MOPED', 'Motorscooter',
       'Concrete Mixer', 'Open Body', 'Beverage Truck', 'fire truck',
       'E-Scooter', 'COMMERCIAL', 'PSD', 'MTA', 'PK', 'Minicycle', 'LIMO',
       'Chassis Cab', 'Tractor Truck Gasoline', 'MACK',
       'Refrigerated Van', 'van', 'Motorbike', 'Fire truck', 'TRUCK',
       'ambulance', 'NYPD VAN', '2 dr sedan', 'Pallet', 'AMBULANE', 'AMB',
       'EMS bus', 'FORKLIFT', 'SANMEN COU', 'FIRE TRUCK', 'forklift',
       'FIRETRUCK', 'School Bus', 'FDNY AMBUL', 'SHUTTLE BU', 'FDNY',
       'NYS Ambula', 'TOW TRUCK', 'Stake or Rack', 'FORD', 'Van Camper',
       'GOLF CAR', 'RV', 'USPS TRUCK', 'Scooter', 'UHAL', 'Dodge',
       'Mini Van', 'SELF INSUR', 'VAN/TRUCK', 'kick scoot', 'SEMI', 'EMS',
       'MTA BUS', 'Cargo van', 'Ambu', 'TRUCK COMM', 'Ford Van',
       'MOTOR SCOO', 'DELIVERY T',
       'Enclosed Body - Nonremovable Enclosure', 'Dirt Bike', 'Skywatch',
       'DUMP TRUCK', 'COM', 'ELECTRIC S', 'Lunch Wagon', 'TL', 'Minibike',
       'Multi-Wheeled Vehicle', 'Hopper', 'UNKNOWN', 'AMBU', 'DIRT BIKE',
       'G COM', 'truck', 'FDNY FIRE', 'Commercial', 'Motorscoot',
       'FORD SPRIN', 'Backhoe Lo', 'Snow Plow', 'REFG', 'POWER LADD',
       'utility tr', 'Mercedes', 'PICKUP', 'firetruck', 'Fire',
       'OML/OMNIBU', 'post offic', 'Well Driller', 'MTA bus', 'Vanette',
       'FDNY ENGIN', 'TRAILER', 'TRAC', 'Fire Truck', 'E-scooter',
       'NYC AMBULA', 'Pickup with mounted Camper', 'Forklift',
       'PASSENGER', 'CMIXER', 'SCOOTER', 'US POSTAL', 'DUMP', 'pickup',
       'TRAILER/FL', 'POSTAL VEH', 'FLAT', 'G PSD', 'USPS', 'PC',
       'Bulk Agriculture', 'HERTZ RAM', 'Fire Engin', 'SUBN - AMB',
       'SPARK150 S', 'MTA Bus', 'TRAILEE', 'UPS TRUCK', 'SPECIAL CO',
       'Quality tr', 'box truck', 'con ed tru', 'FORD VAN', 'UTIL',
       'ford', 'BOX TRUCK', 'Pick up', 'Amb', 'SUBURBAN', 'Unk', '4DS',
       'FDNY TRUCK', 'sanitaion', 'POWER SHOV', 'Ram Promas',
       'SKID LOADE', 'MARKED VAN', 'Power Shov', 'BULLDOZER',
       'SANITATION', 'Excavator', 'SKYWATCH', 'box', 'sedan',
       'Glass Rack', 'Postal tru', 'SNOW PLOW', 'Dump truck', 'TRK',
       'Van truck', 'FDNY EMS', 'VAN TRUCK', 'STAK', 'TRACTOR', 'na',
       'Government', 'Sanitation', 'G AMB', 'tow', 'UTILITY WH',
       'pick up', 'Fedex', 'PICK UP TR', 'U HAUL TRU', 'Subr',
       'USPS Truck', 'Pick up tr', 'fdny ambul', 'Sprinter v',
       'FORK LIFT', 'nyc EMS', 'REP', 'Com', 'DELV', 'unknown', 'Unknown',
       'Box truck', 'Ambulette', 'USPS truck', 'FDNY FIRET', 'util',
       'EMS Ambula', 'LADDER TRU', 'sanitaton', 'tk',
       'Enclosed Body - Removable Enclosure', 'ebike', 'SEDAN', 'PERM',
       'Firetruck', 'FIRE', 'MOTOR HOME', 'mini van', 'UTILITY VE',
       'CMIX', 'usps truck', 'tr', 'TANK', 'Grumman LL', '994',
       'AMBULENCE', 'trailer', 'Dent and S', 'Pick wh', 'PAS',
       'NYC SANITA', 'gas scoote', 'NYS AMBULA', 'DODGE RAM', 'HWH',
       'Unmarked V', 'BOX', 'Gas scoote', 'CHERV', 'Post offic',
       'SKATEBOARD', 'USPS MAIL', 'crane boom', 'sprinter v',
       'MOVING TRU', 'Yamaha', 'PICK UP', 'MINI BUS', 'Fork lift',
       'commerical', 'SEDONA', 'FDNY LADDE', 'Mopd', 'Pedicab',
       'UTILITY VA', 'GAS POWERE', 'ENGINE SP0', 'Pass', 'US Mail Tr',
       'gas mo ped', 'SCOOTER GA', 'Pro master', 'Truck', 'forlift',
       'Can', 'FLATBED FR', 'postal van', 'UNK', 'FIRTRUCK', 'TTAILER',
       'fdny ems', 'AMBULACE', 'bus', 'Street Swe', 'FDNY fire',
       'DELIVERY', 'Cement Tru', 'USPS/GOVT', 'TRUCK VAN', 'SUV',
       'CATAPILLAR', 'utility', 'SWT', 'FLAT  BED', 'E-BIKE', 'Fork Lift',
       'UTILITY', 'Courier', 'SMART CAR', 'E-UNICYCLE', 'Street Cle',
       'F550', 'BICYCLE', 'ford van', 'commercial', 'FDNY Engin',
       'Go kart', 'CHEVY EXPR', 'SLINGSHOT', 'dilevery t', 'FDNY #226',
       'UNKN', 'MOVING VAN', 'usps', 'moped', 'backhoe', 'Delv',
       'dump truck', 'Horse', 'BOBCAT FOR', 'Pumper', 'DOT EQUIPM',
       'Livestock Rack', 'GEN  AMBUL', '18 WHEELER', 'MOTORSCOOT',
       'Front-Load', 'DRILL RIG', 'Wh Ford co', 'suburban', 'E REVEL SC',
       'ROAD SWEEP', 'LIGHT TRAI', 'Tractor', 'cross', 'Bucket Tru',
       'JOHN DEERE', 'BACK HOE', 'postal tru', 'CHEVROLET', 'Fdny ambul',
       'NYC FD', 'E-bike', 'FUSION', 'GOLF CART', 'POSTAL TRU',
       'FIRE ENGIN', 'Ford sprin', 'Work van', 'FREIG', 'FLATBED', 'ambu',
       'tow truck', 'Pick up Tr', '0', 'postal bus', 'government', 'CAT',
       'E bike', 'FDNY Fire', 'com', 'CARGO VAN', 'ELEC. UNIC',
       'Motorized Home', 'WORK VAN', 'DEPARTMENT', 'FDNY Firet', 'Self',
       'E scooter', 'E-SCOOTER', '50cc Scoot', 'Tow Truck', 'Cement tru',
       'work truck', 'FDNY Truck', 'Mack Truck', 'VMS', 'TLR',
       'Constructi', 'School bus', 'SCHOOL  BU', 'NonMotordS', 'Mack',
       'police rep', 'EC3', 'ECONOLINE', 'UPS', 'VAN WH', 'USPS POSTA',
       'White ambu', 'FREIGHT TR', 'TRL', 'FREIGHTLIN', 'pc', 'delviery',
       'E-Bik', 'Horse Trai', 'escavator', 'OMR', 'P/SH', 'ford econo',
       'pick', 'MAIL TRUCK', 'USPS #7530', 'Hearse', 'SE', 'PUSH SCOOT',
       'Delivery', 'postal ser', 'PICKUP TRU', 'nat grid t', 'G com',
       'backh', 'D/V WB', 'Bobcat', 'UTILITY TR', 'food truck',
       'EMERGENCY', 'fdny truck', 'pay loader', 'tractor tr',
       'FDNY EMS V', 'RV/VAN', 'TR-Trailer', 'ESU RESCUE', 'City',
       'pedicab', 'I-haul', 'BOOM LIFT', 'U-Haul min', 'Pickup tru',
       'freight', '12 PASSENG', 'STREET SWE', '12 passage', 'STREET CLE',
       'PUMPER', 'LOCOMOTIVE', 'Horse carr', 'YELLOWPOWE', '197209',
       'posta', 'E450', 'UTILI', 'SCHOO', 'TRAIL', 'utili', 'St', 'E-Sco',
       'amulance', 'DEPT VAN #', 'MOPD', 'GRUMM', 'FIRET', 'Wagon',
       'AMBUL', 'PSH', 'US PO', 'TRACT', 'BOX T', 'UHUAL', 'BACKH',
       'DELVI', 'box t', 'SCOOT', 'picku', 'trail', 'DELIV', 'FORKL',
       'van t', 'SKATE', 'PAYLO', 'SANIT', 'Forkl', 'ECONO', 'tract',
       'FUEL', 'TRC', 'Ambul', 'TANKE', 'GARBA', '3 WHE', 'road', 'DOT T',
       'CRANE', 'MTA B', 'FLAT/', 'deliv', 'COMME', 'scoot', 'Box T',
       'schoo', 'STREE', 'FEDEX', 'LIEBH', 'CAB', 'TOW T', 'USP M',
       'SANTI', 'tow t', 'prks', 'Unkno', 'limo', 'ambul', 'g spc',
       'CONT', 'HI TA', 'CAT.', 'POLIC', 'Parce', 'PICKU', 'fire', 'COMM',
       '35 FT', 'Trail', 'GOLF', 'UT', 'PU', 'forkl', 'Tow T', 'TOWTR',
       'PICK-', 'E BIK', 'POWER', 'UNKNO', 'ELECT', 'MINI', 'stree',
       'elect', 'Golf', 'FORK', 'Sprin', 'CITY', 'UHAUL', 'BS', 'APPOR',
       'Scoot', 'Mta', 'Van T', 'SELF', 'SKID-', 'E SCO', 'DIRT', 'ICE C',
       'motor', 'KUBOT', 'NYS A', 'range', 'BULLD', 'ACCES', 'Barri',
       'subn', 'VAN T', 'MAIL', 'Acces', 'Motor', 'BTM', 'Pas', 'NTTRL',
       'MOTOR', 'YELLO', 'TRLR', 'firet', 'movin', 'nypd', 'SUBUR',
       'Rescu', 'E-BIK', 'COURI', 'NAVIG', 'Subn', 'mta b', 'COMMU',
       'ROAD', 'TIR', 'st', 'Motor Home', 'WAGON', 'TRACK EXCA', 'dumps',
       'semi', 'Stree', 'CAT P', 'power', 'garba', 'wagon', 'Garba',
       'BOOM', 'Comme', 'RMP', 'fdny', 'SEGWA', 'comme', 'SC', 'Deliv',
       'cater', 'Tow t', 'SEA', 'moter', 'Hrse', 'U-Hau', 'BUCKE', 'Mail',
       'Sanit', 'BK', 'NYCHA', 'Snow', 'COMER', 'Pick', 'Picku', 'NYPD',
       'US Po', 'TKTR', 'GATOR', 'Box t', 'VAV', 'Const', 'EXCAV', 'none',
       'Road', 'Firet', 'GOVER', 'te', 'LTRL', 'Tract', '\x7fomm',
       'TRANS', 'MAC T'], dtype=object)

In [35]:
## If "unusual" means weird... here's some strange vehicles
## Back Hoe, Van Camper, Horse cart, Go Kart, and Golf kart

In [47]:
## my filters

fil_queens = nyc_accidents["BOROUGH"] == "QUEENS"
fil_manhattan = nyc_accidents["BOROUGH"] == "MANHATTAN"
fil_bronx = nyc_accidents["BOROUGH"] == "BRONX"
fil_brooklyn = nyc_accidents["BOROUGH"] == "BROOKLYN"
fil_staten_island = nyc_accidents["BOROUGH"] == "STATEN ISLAND"
fil_taxi = nyc_accidents["VEHICLE TYPE CODE 1"] == "Taxi"

In [38]:
df_q = nyc_accidents[fil_queens]

In [39]:
df_q

,CRASH DATE,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
2,4/13/21,17:30,QUEENS,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4408019,Sedan,Sedan
10,4/14/21,21:43,QUEENS,0,0,0,0,0,0,0,0,Turning Improperly,Unspecified,4407407,Station Wagon/Sport Utility Vehicle,NaN
17,4/15/21,14:30,QUEENS,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Driver Inattention/Distraction,4407616,Sedan,Station Wagon/Sport Utility Vehicle
27,4/16/21,11:00,QUEENS,1,0,0,0,1,0,0,0,Turning Improperly,Unspecified,4407792,Station Wagon/Sport Utility Vehicle,Bike
28,4/16/21,17:00,QUEENS,5,0,0,0,0,0,5,0,Traffic Control Disregarded,Unspecified,4407853,Sedan,Station Wagon/Sport Utility Vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282861,1/1/19,11:00,QUEENS,0,0,0,0,0,0,0,0,Unspecified,NaN,4065827,Sedan,NaN
282862,1/1/19,12:30,QUEENS,0,0,0,0,0,0,0,0,Unspecified,NaN,4062343,Sedan,NaN
282863,1/1/19,2:18,QUEENS,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4060413,Sedan,NaN
282864,1/1/19,13:00,QUEENS,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4060511,Sedan,Sedan
282866,1/1/19,10:23,QUEENS,1,0,0,0,0,0,1,0,Failure to Keep Right,Failure to Keep Right,4059208,Station Wagon/Sport Utility Vehicle,Sedan

In [40]:
### This is for the total number of deaths in queens accidents

In [43]:
df_q["NUMBER OF PERSONS KILLED"].sum()

120

In [44]:
## 120 people were killed in Queens

In [45]:
df_q["NUMBER OF CYCLIST KILLED"].sum()

8

In [46]:
## 8 cyclists were killed in Queens

In [48]:
df_m_taxi = nyc_accidents[fil_manhattan & fil_taxi]

In [49]:
df_m_taxi

,CRASH DATE,CRASH TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2
67,4/14/21,8:03,MANHATTAN,1,0,1,0,0,0,0,0,Driver Inattention/Distraction,NaN,4407277,Taxi,NaN
144,4/14/21,0:42,MANHATTAN,0,0,0,0,0,0,0,0,Unspecified,Unspecified,4407278,Taxi,Sedan
159,4/16/21,19:54,MANHATTAN,0,0,0,0,0,0,0,0,Unspecified,NaN,4407959,Taxi,NaN
283,4/16/21,21:04,MANHATTAN,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,NaN,4408288,Taxi,NaN
326,4/16/21,16:15,MANHATTAN,0,0,0,0,0,0,0,0,Driver Inattention/Distraction,Unspecified,4408069,Taxi,Bus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282632,1/1/19,1:30,MANHATTAN,0,0,0,0,0,0,0,0,Other Vehicular,Driver Inattention/Distraction,4060445,Taxi,Station Wagon/Sport Utility Vehicle
282684,1/1/19,16:00,MANHATTAN,2,0,0,0,0,0,2,0,Traffic Control Disregarded,Unspecified,4061524,Taxi,Station Wagon/Sport Utility Vehicle
282802,1/1/19,16:15,MANHATTAN,0,0,0,0,0,0,0,0,Passenger Distraction,Passing Too Closely,4060796,Taxi,Sedan
282819,1/1/19,20:30,MANHATTAN,0,0,0,0,0,0,0,0,Unspecified,NaN,4060662,Taxi,NaN
282851,1/1/19,6:00,MANHATTAN,0,0,0,0,0,0,0,0,Unspecified,NaN,4060698,Taxi,NaN

In [50]:
## top 5 causes of accidents in all boroughs by primary vehicle factor
nyc_accidents["CONTRIBUTING FACTOR VEHICLE 1"].value_counts().head()

Unspecified                       78494
Driver Inattention/Distraction    70615
Failure to Yield Right-of-Way     20691
Following Too Closely             14407
Backing Unsafely                  13348
Name: CONTRIBUTING FACTOR VEHICLE 1, dtype: int64

In [51]:
## top 5 causes of accidents in all borough secondary vehicle factor
nyc_accidents["CONTRIBUTING FACTOR VEHICLE 2"].value_counts().head()

Unspecified                       190456
Driver Inattention/Distraction     14186
Other Vehicular                     3529
Failure to Yield Right-of-Way       2233
Passing or Lane Usage Improper      2171
Name: CONTRIBUTING FACTOR VEHICLE 2, dtype: int64

In [52]:
## rarest causes of accidents in all boroughs primary vehicle factor
nyc_accidents["CONTRIBUTING FACTOR VEHICLE 1"].value_counts().tail()

Shoulders Defective/Improper    13
Texting                          8
Cell Phone (hands-free)          8
Windshield Inadequate            3
Listening/Using Headphones       2
Name: CONTRIBUTING FACTOR VEHICLE 1, dtype: int64

In [53]:
## weird causes of accidents
nyc_accidents["CONTRIBUTING FACTOR VEHICLE 1"].unique()

array(['Unspecified', 'Following Too Closely',
       'Driver Inattention/Distraction', 'Passing Too Closely',
       'Passing or Lane Usage Improper', 'Driver Inexperience',
       'Failure to Yield Right-of-Way', 'Turning Improperly',
       'Unsafe Speed', 'Backing Unsafely', 'Steering Failure',
       'Traffic Control Disregarded', 'Drugs (illegal)',
       'Reaction to Uninvolved Vehicle', 'View Obstructed/Limited',
       'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion',
       'Alcohol Involvement', 'Pavement Slippery', 'Brakes Defective',
       'Oversized Vehicle', 'Animals Action', 'Unsafe Lane Changing',
       'Outside Car Distraction', 'Illnes', 'Other Vehicular',
       'Aggressive Driving/Road Rage', 'Fell Asleep',
       'Tire Failure/Inadequate', 'Pavement Defective', nan,
       'Lost Consciousness', 'Accelerator Defective',
       'Passenger Distraction', 'Glare', 'Eating or Drinking',
       'Cell Phone (hands-free)', 'Lane Marking Improper/Inadequate',
       'Obstruction/Debris', 'Failure to Keep Right',
       'Using On Board Navigation Device', 'Fatigued/Drowsy',
       'Physical Disability', 'Cell Phone (hand-Held)',
       'Headlights Defective', 'Tinted Windows', 'Vehicle Vandalism',
       'Driverless/Runaway Vehicle', 'Prescription Medication', 'Texting',
       'Traffic Control Device Improper/Non-Working',
       'Tow Hitch Defective', 'Shoulders Defective/Improper',
       'Windshield Inadequate', 'Other Lighting Defects',
       'Other Electronic Device', 'Listening/Using Headphones'],
      dtype=object)

In [56]:
nyc_accidents["CONTRIBUTING FACTOR VEHICLE 2"].unique()

array([nan, 'Unspecified', 'Unsafe Speed',
       'Driver Inattention/Distraction', 'Failure to Yield Right-of-Way',
       'Turning Improperly', 'Driver Inexperience',
       'Following Too Closely', 'View Obstructed/Limited',
       'Oversized Vehicle', 'Passing Too Closely', 'Other Vehicular',
       'Traffic Control Disregarded', 'Passing or Lane Usage Improper',
       'Reaction to Uninvolved Vehicle', 'Backing Unsafely',
       'Alcohol Involvement', 'Outside Car Distraction',
       'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion',
       'Obstruction/Debris', 'Aggressive Driving/Road Rage',
       'Vehicle Vandalism', 'Pavement Slippery', 'Unsafe Lane Changing',
       'Passenger Distraction', 'Fell Asleep',
       'Driverless/Runaway Vehicle', 'Drugs (illegal)', 'Fatigued/Drowsy',
       'Brakes Defective', 'Headlights Defective',
       'Failure to Keep Right', 'Glare', 'Other Lighting Defects',
       'Traffic Control Device Improper/Non-Working',
       'Cell Phone (hands-free)', 'Lane Marking Improper/Inadequate',
       'Pavement Defective', 'Tinted Windows', 'Cell Phone (hand-Held)',
       'Listening/Using Headphones', 'Steering Failure',
       'Tow Hitch Defective', 'Tire Failure/Inadequate', 'Illnes',
       'Lost Consciousness', 'Other Electronic Device', 'Animals Action',
       'Prescription Medication', 'Accelerator Defective',
       'Shoulders Defective/Improper', 'Using On Board Navigation Device',
       'Physical Disability', 'Eating or Drinking', 'Texting'],
      dtype=object)

In [57]:
##If "unusual" means infrequent:
## Unusual primary vehicle contributing factors:
##Shoulders Defective/Improper','Windshield Inadequate', 'Other Lighting Defects',
##'Other Electronic Device', 'Listening/Using Headphones'

In [58]:
## Unusual secondary vehicle factors:
## Shoulders Defective/Improper', 'Using On Board Navigation Device',
## 'Physical Disability', 'Eating or Drinking', 'Texting'